-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  role text check (role in ('client', 'tasker')) default 'client',
  bio text,
  location text,
  phone text,
  skills text,
  hourly_rate numeric,
  availability text
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

create policy "Users can delete their own profile."
  on profiles for delete
  using ( auth.uid() = id );

create policy "Admins can delete any profile."
  on profiles for delete
  using ( auth.uid() in (select id from profiles where role = 'admin') );

-- Create a table for services
create table services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  icon text, -- Store icon name or url
  base_price numeric
);

alter table services enable row level security;

create policy "Services are viewable by everyone."
  on services for select
  using ( true );

-- Create a table for tasks
create table tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id uuid references profiles(id) not null,
  tasker_id uuid references profiles(id), -- Nullable until a tasker accepts
  service_id bigint references services(id) not null,
  title text not null,
  description text,
  location text not null,
  status text check (status in ('open', 'assigned', 'completed', 'cancelled')) default 'open',
  price numeric,
  scheduled_date timestamp with time zone
);

alter table tasks enable row level security;

create policy "Tasks are viewable by everyone."
  on tasks for select
  using ( true );

create policy "Clients can create tasks."
  on tasks for insert
  with check ( auth.uid() = client_id );

create policy "Clients can update their own tasks."
  on tasks for update
  using ( auth.uid() = client_id );

create policy "Taskers can update tasks they are assigned to (or accept open tasks)."
  on tasks for update
  using ( auth.uid() = tasker_id or (tasker_id is null and status = 'open') );

create policy "Clients can delete their own tasks."
  on tasks for delete
  using ( auth.uid() = client_id );

create policy "Admins can delete any task."
  on tasks for delete
  using ( auth.uid() in (select id from profiles where role = 'admin') );

-- Create a table for reviews
create table reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  task_id bigint references tasks(id) not null,
  reviewer_id uuid references profiles(id) not null,
  reviewee_id uuid references profiles(id) not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text
);

alter table reviews enable row level security;

create policy "Reviews are viewable by everyone."
  on reviews for select
  using ( true );

create policy "Authenticated users can create reviews."
  on reviews for insert
  with check ( auth.uid() = reviewer_id );

-- Insert default services
insert into services (name, description, icon, base_price) values
('House Cleaning', 'General cleaning for your home.', 'FaBroom', 50),
('Car Wash', 'Exterior and interior car cleaning.', 'FaCar', 30),
('Laundry Cleaning', 'Wash, dry, and fold laundry services.', 'FaTshirt', 20),
('Garden Services', 'Lawn mowing, trimming, and general garden maintenance.', 'FaTree', 60),
('Weed Removal', 'Removing weeds from your garden or driveway.', 'FaLeaf', 40),
('Home Repairs', 'General home repairs like fixing doors, cabinets, etc.', 'FaTools', 70),
('Plumbing', 'Fixing leaks, unclogging drains, and other plumbing tasks.', 'FaWrench', 80);
